let doct=document.getElementById("p1");
doct.innerHTML="Name:....."
let doct1=document.getElementById("p2");
doct1.innerHTML="Education:B.Tech"
let doct3=document.getElementById("p3");
doct3.innerHTML="Age:0"
let doct4=document.getElementById("p4");
doct4.innerHTML="ExpectedSalary:0"
// let doct=document.getElementById("p1");
// doct.innerHTML="Name:....."
